# Generated by Django 3.2.7 on 2021-10-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_address',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
