# Generated by Django 3.2.7 on 2021-10-12 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20211012_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
