# Generated by Django 3.2.7 on 2021-10-04 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=10, null=True)),
                ('total_quantity', models.CharField(blank=True, default=1, max_length=10, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('remaining_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('cash_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('cash_returned', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status_for_accepted', models.BooleanField(default=True)),
                ('dho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
